services:
  - type: worker
    name: telegram-audio-bot
    runtime: python
    region: frankfurt
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      apt-get update
      apt-get install -y ffmpeg
    startCommand: |
      python manage.py runbot
    envVars:
      - key: BOT_TOKEN
        sync: false
